### PR TITLE
2.1.0 pre-release

### PR DESCRIPTION
**Pull request by jacopoabramo**
Minor update containing a lot of changes from UC2 developers

- added various UC2 controller-widgets-managers
- added initial support for new plugin system
- added support for installation on ARM64
- various bug-fixes on existing modules
- added no-Qt version of ImSwitch framework
- added full support for headless mode (no viewer layer; still requires documentation)
- added dockers for local deployment

Although a lot of code has been added, we are making sure that this is not backwards compatible with the current ImSwitch status. It is a pre-release and will not be published until we are satisfied with the result.

All discussion related to the new release should go in this PR.

@beniroquai please let me know if I'm forgetting something.

### CODE REVIEW

**Comment by beniroquai** [comment]
Thanks Jacopo! I think there is also some major changes in the fastapi parts so that more functions get exposed and images can be streamed. If I may file another PR to the dev branch, we get the fully-working headless version, too. Then no QT is required anymore. The headless in this dev version only comes without launching the widgets, but still relies on all the QT signals, etc.

**Comment by jacopoabramo** [comment]
Is the non-Qt version back-compatible?

**Comment by beniroquai** [comment]
As of now, yes. Changed some things last week and update the
openuc2/imSwitch master branch.

**Comment by jacopoabramo** [comment]
You think it would be possible to open the PR on the 14th? I would like to freeze all further feature develop and focus on refactoring, cleanup and documentation after this release.

**Comment by beniroquai** [comment]
14th of August? Certainly. I'm doing the same. 
One more bigger thing I have added to Imswitch is a very rudimentary command-line interface by means of arguments on launch. This is necessary for the Docker stuff. I managed to have Docker running on a raspi with a 2-line installation "experience". We're getting there. Usecase: https://github.com/openUC2/openUC2_SOOP?tab=readme-ov-file#installation
This, with arkitekt from @jhnnsrs is a very powerful combination - I hope! :)

**Comment by beniroquai** [comment]
So, what can I do? "Simply" do a new PR into the dev branch?

**Comment by jacopoabramo** [comment]
> So, what can I do? "Simply" do a new PR into the dev branch?

Could you please launch some local unit tests before that?

**Comment by jacopoabramo** [comment]
@beniroquai can you approve the review? I would like to do so myself but apparently I can't. Otherwise I'm blocked from merging.

**Comment by beniroquai** [comment]
Done.

**Pull request merged**
