### PR TITLE
Bringing UC2 to dev branch

### PR DESCRIPTION
**Pull request by jacopoabramo**
Merging from the old UC2 branch in the dev branch for next release

### CODE REVIEW

**Comment by jacopoabramo** [comment]
@beniroquai I created a new PR from the UC2 branch to dev. If you want to do new changes you should do them in the UC2 branch of the main repository so it keeps track of it.

**Comment by jacopoabramo** [comment]
@beniroquai your old friend, segmentation fault, is back at it again

**Comment by beniroquai** [comment]
I know @jacopoabramo, Honestly, I have absolutely no clue why this is happening. I cannot reproduce the error on my Mac unfortunately.

**Comment by beniroquai** [comment]
@jacopoabramo do you want to merge it now? ;) 
Last activity in the repo is ~7 month ago :p

**Comment by jacopoabramo** [comment]
I know but I don't feel comfortable merging without investigating why the tests are failing.

**Comment by jacopoabramo** [comment]
@kasasxav sorry for constantly bothering you but... Did you ever experience these segfault errors in the UT? Only macOS tests seem to fail

**Comment by jacopoabramo** [comment]
Or rather: the tests actually pass successfully but then the runners go in segmentation fault

**Comment by kasasxav** [comment]
Hi @jacopoabramo , no worries at all!

I have no idea, but sometimes it happened that some of them failed (I think that's why I removed the linux ones :l). Could you try to re-run them? Sometimes that fixed it.

BEst,
Xavier.

**Comment by jacopoabramo** [comment]
I decided to approve this PR nonetheless. The tests are all passing; we will have to still investigate the issue related to the segmentation fault on macOS. I realized it should not be much trouble for users anyway.

**Pull request merged**
